=== yabfc/yabfc/profiles/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://raw.githubusercontent.com/yabfc/yabfc/refs/heads/main/profiles/schema.json",
	"$defs": {
		"recipe-io": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"amount": {
						"type": "number"
					},
					"type": { "type": "string", "enum": ["item", "fluid"] }
				},
				"required": ["name", "amount"]
			},
			"minItems": 1
		},
		"logistic-transport": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"throughput": {
					"type": "number"
				},
				"duration": {
					"type": "number",
					"description": "(in seconds)"
				}
			},
			"required": ["name", "throughput", "duration"]
		},
		"logistics": {
			"type": "object",
			"properties": {
				"available_conveyor_belts": {
					"type": "array",
					"description": "should be used if mods are used",
					"items": {
						"$ref": "#/$defs/logistic-transport"
					}
				},
				"available_pipes": {
					"type": "array",
					"description": "should be used if mods are used",
					"items": {
						"$ref": "#/$defs/logistic-transport"
					}
				}
			}
		},
		"satisfactory-limitations": {
			"type": "object",
			"properties": {
				"unlocked_milestones": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"unlocked_alternate_recipes": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"overclocking": {
					"type": "boolean"
				},
				"summerslooping": {
					"type": "boolean"
				}
			},
			"required": [
				"unlocked_milestones",
				"unlocked_alternate_recipes",
				"overclocking",
				"summerslooping"
			]
		},
		"factorio-limitations": {
			"type": "object",
			"properties": {
				"unlocked_research": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"spaceage": {
					"type": "boolean"
				}
			},
			"required": ["unlocked_research", "spaceage"]
		}
	},
	"title": "YABFC Satisfactory Schema",
	"type": "object",
	"properties": {
		"title": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"type": {
			"enum": ["satisfactory", "factorio"]
		},
		"limitations": {
			"$ref": "#/$defs/logistics"
		},
		"recipes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"in": {
						"$ref": "#/$defs/recipe-io"
					},
					"out": {
						"$ref": "#/$defs/recipe-io"
					},
					"duration": {
						"type": "number"
					},
					"produced_in": {
						"type": "array",
						"items": {
							"type": "string"
						},
						"minItems": 1
					}
				},
				"required": ["in", "out", "duration", "produced_in"]
			}
		}
	},
	"if": {
		"properties": {
			"type": {
				"const": "satisfactory"
			}
		}
	},
	"then": {
		"properties": {
			"limitations": {
				"$ref": "#/$defs/satisfactory-limitations"
			}
		}
	},
	"else": {
		"properties": {
			"limitations": {
				"$ref": "#/$defs/factorio-limitations"
			}
		}
	}
}

=== yabfc/yabfc/profiles/example_factorio.json
{
	"title": "my great factory",
	"description": "I love factories",
	"type": "factorio",
	"limitations": {
		"available_conveyor_belts": [
			{
				"name": "transport-belt",
				"throughput": 15,
				"duration": 1
			},
			{
				"name": "fast-transport-belt",
				"throughput": 30,
				"duration": 1
			}
		],
		"spaceage": true,
		"unlocked_research": ["uranium_processing", "oil_processing", "space_platform"]
	},
	"recipes": [
		{
			"in": [
				{
					"name": "iron-ore",
					"amount": 1
				}
			],
			"out": [
				{
					"name": "iron-plate",
					"amount": 1
				}
			],
			"duration": 3.2,
			"produced_in": ["stone_furnace", "steel_furnace", "electric_furnace"]
		},
		{
			"in": [
				{
					"name": "copper-ore",
					"amount": 1
				}
			],
			"out": [
				{
					"name": "copper-plate",
					"amount": 1
				}
			],
			"duration": 3.2,
			"produced_in": ["stone-furnace", "steel-furnace", "electric-furnace"]
		},
		{
			"in": [
				{
					"name": "copper-plate",
					"amount": 1
				}
			],
			"out": [
				{
					"name": "copper-cable",
					"amount": 2
				}
			],
			"duration": 0.5,
			"produced_in": ["assembling-machine"]
		},
		{
			"in": [
				{
					"name": "copper-cable",
					"amount": 3
				},
				{
					"name": "iron-plate",
					"amount": 1
				}
			],
			"out": [
				{
					"name": "electronic-circuit",
					"amount": 1
				}
			],
			"duration": 0.5,
			"produced_in": ["assembling-machine"]
		}
	]
}

=== yabfc/yabfc/profiles/example_satisfactory.json
{
	"title": "my other great factory",
	"description": "I love factories",
	"type": "satisfactory",
	"limitations": {
		"available_conveyor_belts": [
			{
				"name": "conveyor-belt-mk1",
				"throughput": 60,
				"duration": 60
			},
			{
				"name": "conveyor-belt-mk2",
				"throughput": 120,
				"duration": 60
			},
			{
				"name": "conveyor-belt-mk3",
				"throughput": 270,
				"duration": 60
			},
			{
				"name": "conveyor-belt-mk4",
				"throughput": 480,
				"duration": 60
			},
			{
				"name": "conveyor-belt-mk5",
				"throughput": 780,
				"duration": 60
			},
			{
				"name": "conveyor-belt-mk6",
				"throughput": 1200,
				"duration": 60
			}
		],
		"available_pipes": [
			{
				"name": "pipeline-mk1",
				"throughput": 300,
				"duration": 60
			},
			{
				"name": "pipeline-mk2",
				"throughput": 600,
				"duration": 60
			}
		],
		"overclocking": true,
		"summerslooping": false,
		"unlocked_alternate_recipes": [],
		"unlocked_milestones": ["uranium_processing", "oil_processing", "space_platform"]
	},
	"recipes": [
		{
			"in": [
				{
					"name": "iron-ore",
					"amount": 30
				}
			],
			"out": [
				{
					"name": "iron-ingot",
					"amount": 30
				}
			],
			"duration": 60,
			"produced_in": ["smelter"]
		},
		{
			"in": [
				{
					"name": "copper-ore",
					"amount": 30
				}
			],
			"out": [
				{
					"name": "copper-ingot",
					"amount": 30
				}
			],
			"duration": 60,
			"produced_in": ["smelter"]
		},
		{
			"in": [
				{
					"name": "iron-plate",
					"amount": 30
				},
				{
					"name": "screw",
					"amount": 60
				}
			],
			"out": [
				{
					"name": "reinforced-iron-plate",
					"amount": 60
				}
			],
			"duration": 60,
			"produced_in": ["assembler"]
		}
	]
}
